image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.7

sources:
  - ingress

provider: aws

domainFilters:
 - cmcloudlab855.info

annotationFilter: "kubernetes.io/ingress.class=nginx-internal"

registry: "txt"
txtPrefix: "txt."
txtOwnerId: myekscluster.private-external-dns

## options: sync, upsert-only
policy: sync
logLevel: info

rbac:
 serviceAccountName: external-dns
