image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.7

sources:
  - service

provider: aws

domainFilters:
 - cmcloudlab855.info

registry: "txt"
txtPrefix: "txt."
txtOwnerId: myekscluster.nginx-external-dns

## options: sync, upsert-only
policy: sync
logLevel: info

rbac:
 serviceAccountName: external-dns
