rbac:
  create: true
  pspEnabled: true
serviceAccount:
  create: true
  name:

replicas: 1

image:
  repository: grafana/grafana
  tag: 5.1.3
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/acme-dns01-provider: "route53"
    external-dns.alpha.kubernetes.io/hostname: grafana.eks.CLUSTER_DNS
    external-dns.alpha.kubernetes.io/target: internal.nginx.eks.CLUSTER_DNS

  labels: {}
  path: /
  hosts:
    -  grafana.eks.CLUSTER_DNS

  tls:
    - secretName: grafana-crt
      hosts:
        - grafana.eks.CLUSTER_DNS

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

adminUser: blueharvest
adminPassword: grafana

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi

datasources: 
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server.monitoring.svc.cluster.local
     access: proxy
     isDefault: true

dashboardsConfigMaps:
  default-dashboards: "default-dashboards"
  istio-dashboards: "istio-dashboards"
  istio-system-dashboards: "istio-system-dashboards"

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default-dashboards'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default-dashboards
    - name: 'istio-dashboards'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/istio-dashboards
    - name: 'istio-system-dashboards'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/istio-system-dashboards
