---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: "kube-system"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: LETSENCRYPT_EMAIL
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the DNS-01 challenge provider
    dns01:
      providers:
      - name: route53
        route53:
          hostedZoneID: Z07189641W9G8LFB5AE3Y
          accessKeyID: 
          secretAccessKeySecretRef:
            name: route53-config
            key: secret-access-key
          region: us-east-1
